version: "3.9"
services:
  mq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  restore_service:
    image: restore_service:latest
    restart: unless-stopped
    environment:
        - MQ_HOST=mq
  arcane_service:
    image: arcane_service:latest
    restart: unless-stopped
    environment:
        - MQ_HOST=mq
